import { signal, css } from "@kanabun/core";

/**
 * A small two-page app shared by the build (`renderToString`, once per route)
 * and the client (`hydrate`). The page content is chosen from `path` — read
 * once, since it's fixed for a prerendered page — while the counter is reactive
 * so the hydrated page is interactive.
 */
export function App(props: { path: string }) {
  // Scoped styles. Emitted during the render (server) or hydration (client), so
  // they collect into the prerendered <head> and the client dedupes against the
  // server-sent <style> by its `data-k` hash.
  const shell = css`
    font-family: system-ui, sans-serif;
    max-width: 32rem;
    margin: 4rem auto;
    padding: 0 1rem;
    line-height: 1.6;

    nav a {
      color: #2563eb;
      text-decoration: none;
    }
    nav a:hover {
      text-decoration: underline;
    }

    button {
      font: inherit;
      padding: 0.5rem 1rem;
      border: 1px solid #ccc;
      border-radius: 8px;
      background: #f7f7f7;
      cursor: pointer;
    }
  `;
  const count = signal(0);
  const here = props.path.replace(/\/+$/, "") || "/";
  return (
    <main class={shell}>
      <nav>
        <a href="/">Home</a> · <a href="/about/">About</a>
      </nav>
      {here === "/about" ? (
        <p>
          kanabun prerenders each route to static HTML at build time with the
          same <code>renderToString</code> used for SSR.
        </p>
      ) : (
        <p>
          Welcome. This page was generated by <code>kanabun generate</code> and
          hydrated into a live app.
        </p>
      )}
      <button type="button" onClick={() => count.update((n) => n + 1)}>
        count is <span>{count}</span>
      </button>
    </main>
  );
}
